version: '3.0'
services:
  mysql:
    image: "lutraman/fundmedb"
    # logging:
    #   driver: "none"
    environment:
      - MYSQL_ROOT_PASSWORD=1q2w3e4r
  frontend:
    image: "fundme-frontend"
    environment:
      - LISTEN_PORT=3002
  app:
    image: "fundme-server"
    # entrypoint: '/bin/sh'
    # tty: true
    # stdin_open: true
    environment:
      - mysql__host=mysql
      - mysql__password=1q2w3e4r
      - frontend_static_server=frontend:3002
      - SECRETS_FILE=/configs/secret_settings.json
    volumes:
      - ./docker-entry-scripts/app:/entrypoint.d
      - ./frontend/dist:/frontend
      - ./configs:/configs
    ports:
      - "3000:3000"
