version: '3.0'
services:
  mysql:
    image: "lutraman/fundmedb"
    # logging:
    #   driver: "none"
    environment:
      - MYSQL_ROOT_PASSWORD=1q2w3e4r
  app:
    image: "gcr.io/voost-server/fundme-server:latest"
    # entrypoint: '/bin/sh'
    # tty: true
    # stdin_open: true
    environment:
      - mysql__host=mysql
      - mysql__password=1q2w3e4r
      - frontend_production_dir=/frontend
      - SECRETS_FILE=/configs/secret_settings.json
    volumes:
      - ./docker-entry-scripts/app:/entrypoint.d
      - ./frontend/dist:/frontend
      - ./configs:/configs
    ports:
      - "3000:3000"
  # test:
  #   image: "mhart/alpine-node:11"
  #   environment:
  #     - mysql__host=mysql
  #     - listen_address=app
  #   volumes:
  #     - ./:/code
  #     - ./docker-entry-scripts/test:/entrypoint.d
  #   working_dir: "/code"
  #   command: "/bin/sh"
  #   entrypoint: "./docker-init.sh"
  #   command: "npm test"
